MVC Dashbaord .net5/MVC.PL .net5/MVC.PL/Controllers/EmployeeController.cs
using Microsoft.AspNetCore.Mvc;
using MVC.BLL.Interfaces;
using MVC.DAL.Entites;
using System.Threading.Tasks;
using System;
using MVC.PL.Models;
using AutoMapper;
using System.Collections;
using System.Collections.Generic;
using System.Reflection.Metadata;
using MVC.PL.Helper;

namespace MVC.PL.Controllers
{
    public class EmployeeController : Controller
    {
        private readonly IUnitOfWork unitOfWork;
        private readonly IMapper mapper;

        //private readonly IEmployeeRepository employeeRepository;
        //private readonly IDepartmentRepository departmentRepository;

        public EmployeeController(
            IUnitOfWork unitOfWork
            , IMapper mapper
            //IEmployeeRepository employeeRepository
            //, IDepartmentRepository departmentRepository
            )
        {
            this.unitOfWork = unitOfWork;
            this.mapper = mapper;

            //this.employeeRepository = employeeRepository;
            //this.departmentRepository = departmentRepository;
        }

        public async Task<IActionResult> Index(string SearchValue = "")
        {
            IEnumerable<Employee> employees;
            if (string.IsNullOrEmpty(SearchValue))
            {
                employees = await this.unitOfWork.EmployeeRepository.GetAll();
                //var mappedEmployee = this.mapper.Map<IEnumerable<Employee>,IEnumerable<EmployeeViewModel>>(employees);

            }
            else
            {
                employees = await this.unitOfWork.EmployeeRepository.Search(SearchValue);

            }
            var mappedEmployee = this.mapper.Map<IEnumerable<EmployeeViewModel>>(employees);

            return View(mappedEmployee);

        }
        [HttpGet]
        public async Task<IActionResult> Create()
        {
            ViewBag.Departments = await this.unitOfWork.DepartmentRepository.GetAll();
            return View();
        }
        [HttpPost]
        public async Task<IActionResult> Create(EmployeeViewModel employeeViewModel)
        {
            if (ModelState.IsValid)
            {
                //var MappedEmployee = new Employee() 
                //{
                //    Id = employee.Id,
                //    Name = employee.Name,
                //    Address = employee.Address,
                //    Age = employee.Age,
                //    Email = employee.Email,
                //    IsActive = employee.IsActive,
                //    Salary = employee.Salary,
                //    PhoneNumber = employee.PhoneNumber,
                //    HireDate = employee.HireDate,
                //    DepartmentId = employee.DepartmentId

                //};
                employeeViewModel.ImageUrl = DocumentSettings.UploadFile(employeeViewModel.Image, "Imgs");
                var mappedEmployee = this.mapper.Map<Employee>(employeeViewModel);
                await this.unitOfWork.EmployeeRepository.Add(mappedEmployee);
                return RedirectToAction("Index");
            }
            return View(employeeViewModel);

        }

        public async Task<IActionResult> Details(int? id)
        {
            if (id is null)
                return NotFound();
            var employee = await this.unitOfWork.EmployeeRepository.Get(id);

            var mappedEmployee = this.mapper.Map<EmployeeViewModel>(employee);

            var departmentName = await this.unitOfWork.EmployeeRepository.GetDepartmentByEmploeeId(id);
         
            if (employee == null)
                return NotFound();

            return View(mappedEmployee);
        }

        public async Task<IActionResult> Update(int? id)
        {
            ViewBag.Departments = await this.unitOfWork.DepartmentRepository.GetAll();

            if (id is null)
                return NotFound();

            var employee = await this.unitOfWork.EmployeeRepository.Get(id);

            var mappedEmployee = this.mapper.Map<EmployeeViewModel>(employee);

            if (employee == null)
                return NotFound(); 

            return View(mappedEmployee);
        }
        [HttpPost]

        public async Task<IActionResult> Update(int? id, EmployeeViewModel employeeViewModel)
        {
            if (id != employeeViewModel.Id)
                return NotFound();
            if (ModelState.IsValid)
            {
                try
                {
                    employeeViewModel.ImageUrl = DocumentSettings.UploadFile(employeeViewModel.Image, "Imgs");
                    var mappedEmployee = this.mapper.Map<Employee>(employeeViewModel);
                    await this.unitOfWork.EmployeeRepository.Update(mappedEmployee);
                    return RedirectToAction("Index");
                }
                catch (Exception)
                {
                    return View(employeeViewModel);
                }

            }


            return View(employeeViewModel);
        }
        public async Task<IActionResult> Delete(int? id)
        {
            if (id is null)
                return NotFound();
            var employee = await this.unitOfWork.EmployeeRepository.Get(id);

            if (employee == null)
                return NotFound();

            DocumentSettings.DeleteFile("Imgs", employee.ImageUrl);
            await this.unitOfWork.EmployeeRepository.Delete(employee);
            return RedirectToAction("Index");
            //return View(department);

        }
    }
}

MVC Dashbaord .net5/MVC.PL .net5/MVC.PL/Controllers/RolesController.cs
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Identity;
using Microsoft.AspNetCore.Mvc;
using MVC.DAL.Entites;
using MVC.PL.Models.Account;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;

namespace MVC.PL.Controllers
{
    [Authorize(Roles = "Admin , IT")]
    //[Authorize(Roles = "IT")]

    public class RolesController : Controller
    {
        private readonly RoleManager<IdentityRole> roleManager;
        private readonly UserManager<ApplicationUser> userManager;

        public RolesController(RoleManager<IdentityRole> roleManager, UserManager<ApplicationUser> userManager)
        {
            this.roleManager = roleManager;
            this.userManager = userManager;
        }

        public IActionResult Index()
        {
            var roles = this.roleManager.Roles.ToList();
            return View(roles);
        }
        public IActionResult Create()
        {
            return View();
        }
        [HttpPost]
        public async Task<IActionResult> Create(IdentityRole identityRole)
        {
            if (ModelState.IsValid)
            {
                var result = await this.roleManager.CreateAsync(identityRole);
                if (result.Succeeded)
                    return RedirectToAction("Index");

                foreach (var error in result.Errors)
                    ModelState.AddModelError(string.Empty, error.Description);

                return View(identityRole);

            }
            return View(identityRole);
        }

        public async Task<IActionResult> Details(string id)
        {
            if (id is null)
                return NotFound();

            var role = await this.roleManager.FindByIdAsync(id);

            if (role is null)
                return NotFound();

            return View(role);
        }

        public async Task<IActionResult> Update(string id)
        {
            if (id is null)
                return NotFound();

            var role = await this.roleManager.FindByIdAsync(id);

            if (role is null)
                return NotFound();

            return View(role);
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Update(string id, IdentityRole identityRole)
        {
            if (id != identityRole.Id)
                return BadRequest();

            if (ModelState.IsValid)
            {
                try
                {
                    var role = await this.roleManager.FindByIdAsync(id);

                    role.Name = identityRole.Name;
                    role.NormalizedName = identityRole.Name.ToUpper();

                    var result = await this.roleManager.UpdateAsync(role);

                    if (result.Succeeded)
                        return RedirectToAction("Index");

                    foreach (var error in result.Errors)
                        ModelState.AddModelError(string.Empty, error.Description);
                }
                catch (System.Exception)
                {
                    throw;
                }
            }
            return View(identityRole);
        }

        public async Task<IActionResult> Delete(string id)
        {
            if (id is null)
                return NotFound();


            try
            {
                var role = await this.roleManager.FindByIdAsync(id);

                var result = await this.roleManager.DeleteAsync(role);

                if (result.Succeeded)
                    return RedirectToAction("Index");

                foreach (var error in result.Errors)
                    ModelState.AddModelError(string.Empty, error.Description);
            }
            catch (System.Exception)
            {
                throw;
            }

            return View();
        }

        public async Task<IActionResult> AddOrRemoveUsers(string RoleId)
        {
            var role = await this.roleManager.FindByIdAsync(RoleId);

            if (role is null)
                return NotFound();

            ViewBag.RoleId = RoleId;

            var users = new List<UserInRoleViewModel>();

            foreach (var user in this.userManager.Users)
            {
                var userInRole = new UserInRoleViewModel
                {
                    UserId = user.Id,
                    UserName = user.UserName,
                };

                if (await this.userManager.IsInRoleAsync(user, role.Name)) 
                    userInRole.IsSelected = true;
                else 
                    userInRole.IsSelected = false;

                users.Add(userInRole);
            }

            return View(users);
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> AddOrRemoveUsers(List<UserInRoleViewModel> models, string RoleId)
        {
            var role = await this.roleManager.FindByIdAsync(RoleId);

            if (role is null)
                return NotFound();

            if (ModelState.IsValid)
            {
                foreach (var item in models)
                {
                    var user = await this.userManager.FindByIdAsync(item.UserId);
                    if (user is not null)
                    {
                        if(item.IsSelected && !(await this.userManager.IsInRoleAsync(user, role.Name)))
                            await this.userManager.AddToRoleAsync(user, role.Name);
                        else if(!item.IsSelected && (await this.userManager.IsInRoleAsync(user, role.Name)))
                            await this.userManager.RemoveFromRoleAsync(user, role.Name);

                    }
                }
                return RedirectToAction("Update", new {id = RoleId});
            }

            return View(models);
        }
    }
}

MVC Dashbaord .net5/MVC.PL .net5/MVC.PL/Controllers/UsersController.cs
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Identity;
using Microsoft.AspNetCore.Mvc;
using MVC.DAL.Entites;
using System.Collections.Generic;
using System.Data;
using System.Linq;
using System.Threading.Tasks;

namespace MVC.PL.Controllers
{
    [Authorize(Roles = "Admin")]

    public class UsersController : Controller
    {
        private readonly UserManager<ApplicationUser> userManager;

        public UsersController(UserManager<ApplicationUser> userManager)
        {
            this.userManager = userManager;
        }
        public async Task<IActionResult> Index(string SearchValue = "")
        {
            if (string.IsNullOrWhiteSpace(SearchValue))
            {
                var users = this.userManager.Users.ToList();
                return View(users);

            }
            else
            {
                var user = await this.userManager.FindByEmailAsync(SearchValue);
                return View(new List<ApplicationUser> { user});
            }
        }

        public async Task<IActionResult> Details(string id)
        {
            if (id is null)
                return NotFound();

            var user = await this.userManager.FindByIdAsync(id);

            if (user is null)
                return NotFound();

            return View(user);
        }

        public async Task<IActionResult> Update(string id)
        {
            if (id is null)
                return NotFound();

            var user = await this.userManager.FindByIdAsync(id);

            if (user is null)
                return NotFound();

            return View(user);
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Update(string id, ApplicationUser applicationUser)
        {
            if (id != applicationUser.Id)
                return BadRequest();

            if(ModelState.IsValid)
            {
                try
                {
                    var user = await this.userManager.FindByIdAsync(id);

                    user.UserName = applicationUser.UserName;
                    user.NormalizedUserName = applicationUser.UserName.ToUpper();
                    user.PhoneNumber = applicationUser.PhoneNumber;

                    var result = await this.userManager.UpdateAsync(user);

                    if (result.Succeeded)
                        return RedirectToAction("Index");

                    foreach (var error in result.Errors)
                        ModelState.AddModelError(string.Empty, error.Description);
                }
                catch (System.Exception)
                {
                    throw;
                }
            }
            return View();
        }

        public async Task<IActionResult> Delete(string id)
        {
            if (id is null)
                return NotFound();

           
                try
                {
                    var user = await this.userManager.FindByIdAsync(id);

                    var result = await this.userManager.DeleteAsync(user);

                    if (result.Succeeded)
                        return RedirectToAction("Index");

                    foreach (var error in result.Errors)
                        ModelState.AddModelError(string.Empty, error.Description);
                }
                catch (System.Exception)
                {
                    throw;
                }
            
            return View();
        }

    }
}

MVC Dashbaord .net5/MVC.PL .net5/MVC.PL/Views/Shared/_AuthLayout.cshtml
<!--
Author: Colorlib
Author URL: https://colorlib.com
License: Creative Commons Attribution 3.0 Unported
License URL: http://creativecommons.org/licenses/by/3.0/
-->
<!DOCTYPE html>
<html>
<head>
    <title>Creative Colorlib SignUp Form</title>
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <meta http-equiv="Content-Type" content="text/html; charset=utf-8" />
    <script type="application/x-javascript"> addEventListener("load", function() { setTimeout(hideURLbar, 0); }, false); function hideURLbar(){ window.scrollTo(0,1); } </script>
    <!-- Custom Theme files -->
    <link rel="stylesheet" href="~/css/style.css" />
    <!-- //Custom Theme files -->
    <!-- web font -->
    <link href="//fonts.googleapis.com/css?family=Roboto:300,300i,400,400i,700,700i" rel="stylesheet">
    <!-- //web font -->
</head>
<body>
    <!-- main -->
    <div class="main-w3layouts wrapper">
        <h1>@ViewData["Title"]</h1>
        @RenderBody()
        <!-- copyright -->
        <div class="colorlibcopy-agile">
            <p>© 2023 Colorlib Signup Form. All rights reserved | Powered by <a href="https://www.linkedin.com/in/osama-hassaneen-753670212/" target="_blank">Osama</a></p>
        </div>
        <!-- //copyright -->
        <ul class="colorlib-bubbles">
            <li></li>
            <li></li>
            <li></li>
            <li></li>
            <li></li>
            <li></li>
            <li></li>
            <li></li>
            <li></li>
            <li></li>
        </ul>
    </div>
    <!-- //main -->
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    @await RenderSectionAsync("Scripts", required: false)
</body>
</html>

MVC Dashbaord .net5/MVC.PL .net5/MVC.PL/Views/Shared/_ButtonViewPartial.cshtml
@model string
<td>
    <a class="btn btn-success" asp-action="Details" asp-route-id="@Model">
        <i class="fas fa-eye"></i>Details
    </a>
</td>
<td>
    <a class="btn btn-warning" asp-action="Update" asp-route-id="@Model">
        <i class="fas fa-edit"></i>Update
    </a>
</td>
<td>
    <a class="btn btn-danger" asp-action="Delete" asp-route-id="@Model">
        <i class="fas fa-trash"></i>Delete
    </a>
</td>

MVC Dashbaord .net5/MVC.PL .net5/MVC.PL/Views/Shared/_Layout.cshtml
@inject SignInManager<ApplicationUser> signInManager

<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - MVC.PL</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/site.css" />
</head>
<body>
    <header>
        <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-light bg-white border-bottom box-shadow mb-3">
            <div class="container">
                <a class="navbar-brand" asp-area="" asp-controller="Home" asp-action="Index">MVC.PL</a>
                <button class="navbar-toggler" type="button" data-toggle="collapse" data-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                        aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="navbar-collapse collapse d-sm-inline-flex justify-content-between">
                    <ul class="navbar-nav flex-grow-1">
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Index">Home</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Department" asp-action="Index">Departments</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Employee" asp-action="Index">Employees</a>
                        </li>
                        @if(signInManager.IsSignedIn(User) && User.IsInRole("Admin"))
                        {
                            <li class="nav-item">
                                <a class="nav-link text-dark" asp-area="" asp-controller="Users" asp-action="Index">Users</a>
                            </li>
                            <li class="nav-item">
                                <a class="nav-link text-dark" asp-area="" asp-controller="Roles" asp-action="Index">Roles</a>
                            </li>
                        }

                        <li class="nav-item ml-auto btn-danger rounded">
                            <a class="nav-link text-light" asp-area="" asp-controller="Account" asp-action="SignOut">Sign Out</a>
                        </li>
                    </ul>
                </div>
            </div>
        </nav>
    </header>
    <div class="container">
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>

    <footer class="border-top footer text-muted">
        <div class="container">
            &copy; 2023 - MVC.PL - <a asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
        </div>
    </footer>
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    @await RenderSectionAsync("Scripts", required: false)
</body>
</html>